# Steering
type                  : steering
name                  : scan_ac_level
verbose               : True
output_directory      : None
---
# Camera configuration
type                  : camera_configuration
trigger_configuration : external
fadcs                 : [[0,1,2,3,4,5,6,7,8],[],[]]
---
# CTS configuration
type                  : cts_configuration
cts_angle             : 240.
---
# Trigger configuration
type                  : generator_configuration
config                : master
rate                  : 1000
---
# Writer configruation
type                  : writer_configuration
compression           : zrice
number_of_trhead      : 5
input                 : tcp://localhost:13581
---
# Camera server configuration
type                  : camera_server_configuration
---
# Protocol configuration
type                  : protocol_configuration
name                  : ac_led_scan
levels                : [0,10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200,220,240,260,280,300,
320,340,360,380,400,420,440,460,480,500,520,540,560,580,600,640,680,720,760,800,840,880,920,960,100]
events_per_level      : 10000
