---
# Steering
type                  : steering
name                  : test_writer_server
verbose               : True
---
# Camera Configuration
type                  : camera_configuration
trigger_configuration : external
# fadcs: [[which_boards in _sect1],[which_boards in _sect2],[which_boards in _sect3]]
fadcs                 : [[0,1,2,3,4,5,6,7,8,9],[],[]]
---
# Writer configruation
type                  : writer_configuration
compression           : zrice
number_of_thread      : 5
number_of_events_per_file : 100
input                 : tcp://localhost:13581
---
# Camera Server Configuration
type                  : camera_server_configuration

